### ISSUE TITLE
[Suggestion] Ball color

### ISSUE THREAD

**Issue by wohSi** [bosshaft-GmbH/haxball#1]
This issue is more a suggestion, what you think of doing an auto ball color change when you kick a ball? Also, doing that only for some people like admins of room, etc...?

**Comment by sublime801** [comment]
I like the idea, either both of them are possible. I'll update it soon.

**Comment by sublime801** [comment]
@wohSi This is now implemented. 

Changelog:
[+] Added an option to changing ball color to random colors automatically by every second.
[+] Command version is checking player rights now. Non-admin players will get warning message.
